### ISSUE TITLE
No device discovered, attaching error on logs

### ISSUE THREAD

**Issue by anshul10s** [arevindh/tinxy-hacs#1]
Hi, 
Thanks for writing this custom integration of tinxy. I tried it today with my HA

Getting following errors in logs

```
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 8:08:08 PM (1 occurrences)
Last logged: 8:08:08 PM

Error occurred loading configuration flow for integration tinxy: No module named 'custom_components.tinxy.config_flow'
[home-assistant.log](https://github.com/arevindh/tinxy-hacs/files/7570937/home-assistant.log)
```

Attached the log file too, do let me know if you need any other info.

**Comment by arevindh** [comment]
You can ignore the `config_flow` error , I haven't yet implemented the config_flow method . 

I have a few questions for you in order to help troubleshoot. 

1. How many devices do you have on your account ? 
2. Model of each device.
3. Did you try using it via the REST API ?

**Comment by anshul10s** [comment]
1. I have only 1 device as of now
2. This one: https://tinxy.in/product/tinxy-ac-geyser-smart-wifi-switch/
3. No I am not aware of the REST API spec, can you share?

**Comment by arevindh** [comment]
@anshul10s [Check here](https://gist.github.com/arevindh/253302628ad10eed8126a820c2ecdaec) for the Postman API Collection

**Comment by arevindh** [comment]
Please join their official discord https://discord.gg/4zJvRga7, I will be there in my free time, I can answer your question in real time there.

**Comment by anshul10s** [comment]
Thanks! I tried the REST API yous hared, i can see my device as well as can control it.
But i don't see any device getting auto discovered in my home assistant.

**Comment by arevindh** [comment]
Can you send me the response for `https://backend.tinxy.in/v2/devices/` API , don't forget to remove all `id`'s , `passwords`, `pairingCode`  from the JSON.

> Thanks! I tried the REST API yous hared, i can see my device as well as can control it. But i don't see any device getting auto discovered in my home assistant.

**Comment by anshul10s** [comment]
Response of 
`https://backend.tinxy.in/v2/devices/`

```
[
    {
        "enabled": true,
        "devices": [],
        "deviceTypes": [],
        "notificationOn": false,
        "firmwareVersion": 44,
        "_id": "##",
        "userId": "###",
        "switchType": "SWITCH",
        "name": "Geyser",
        "toggleDelay": 250,
        "registrationDate": "2020-12-30T01:50:07.705Z",
        "mqttPassword": "##",
        "pairingCode": ##,
        "typeId": {
            "primary": true,
            "numberOfRelays": 1,
            "toggleDelay": 0,
            "traits": [
                "action.devices.traits.OnOff"
            ],
            "_id": "##",
            "name": "WIFI_SWITCH_V2",
            "gtype": "action.devices.types.SWITCH"
        },
        "uuidRef": "##",
        "__v": 0
    }
]
```
Here you go i have redacted the Sensitive information

**Comment by arevindh** [comment]
> 
So you don't have something like this in JSON right (`devices` and `deviceTypes`)  ?
![image](https://user-images.githubusercontent.com/693151/142753305-3c1493b6-8b62-4e8e-a807-a8331024167b.png)

**Comment by arevindh** [comment]
@anshul10s 
Fixed in new version `0.1.4` please update and check .

**Comment by mechswitch** [comment]
Its Working !!!
Great work... Thanks !! 👍

**Comment by anshul10s** [comment]
Yes works for me to with new version. Thanks!
