### ISSUE TITLE
No module named 'custom_components.tinxy.config_flow

### ISSUE THREAD

**Issue by ManivannanBA** [arevindh/tinxy-hacs#10]
Error occurred loading configuration flow for integration tinxy: No module named 'custom_components.tinxy.config_flow'
8:49:26 PM – (ERROR) config_entries.py - message first occurred at 8:49:26 PM and shows up 3 times
Setup failed for custom integration tinxy: No setup or config entry setup function defined.
8:49:22 PM – (ERROR) setup.py

**Comment by arevindh** [comment]
You don't have to worry about it.
Config flow is not implemented ye, and it won't affect the working .

**Comment by ManivannanBA** [comment]
yeah, thank you.
