### ISSUE TITLE
Requirements for tinxy not found: ['aiohttp==3.8.1'].

### ISSUE THREAD

**Issue by ManivannanBA** [arevindh/tinxy-hacs#11]
Integration error: tinxy - Requirements for tinxy not found: ['aiohttp==3.8.1'].
Platform error switch.tinxy - Requirements for tinxy not found: ['aiohttp==3.8.1'].
Platform error light.tinxy - Requirements for tinxy not found: ['aiohttp==3.8.1'].
Platform error fan.tinxy - Requirements for tinxy not found: ['aiohttp==3.8.1'].

**Comment by ManivannanBA** [comment]
Upgrading Home Assistant from 2022.11.5 to 2022.12.0, then not able to run Tiny.

**Comment by ManivannanBA** [comment]
For now, downgraded the HA version to 2022.11.5 to solve the issues.

**Comment by arevindh** [comment]
@ManivannanBA Please try latest release `2.1.4`

**Comment by ManivannanBA** [comment]
@arevindh Thank you so much issue is sorted with version HA 2022.12.0
