### ISSUE TITLE
Error while initialisation: KeyError: `'status'` in response of `self.hub.get_device_state()` when init `switch`

### ISSUE THREAD

**Issue by shashwat** [arevindh/tinxy-hacs#13]
home-assistant.log:

Added Logger to understand the response of `self.hub.get_device_state()`

` async def get_device_state(self, id, device_number):
        return await self.tinxy_request(
            'v2/devices/'+id+'/state?deviceNumber='+device_number)`

> 2022-12-31 10:43:21.075 ERROR (MainThread) [custom_components.tinxy.switch] {"state": "ON", "brightness": 0}

Seems like response does not contain: `status` and hence the error during initialisation:

> 2022-12-31 10:43:21.076 ERROR (MainThread) [homeassistant.components.switch] tinxy: Error on device update!
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
>     await task
>   File "/config/custom_components/tinxy/switch.py", line 120, in async_update
>     if resp['status'] == 1:
> KeyError: 'status'
>

**Comment by arevindh** [comment]
@shashwat please give your installation version, both HA and integration, List of devices on the account

**Comment by shashwat** [comment]
@arevindh 
HA version:
Home Assistant 2022.12.8
Frontend 20221213.1 - latest

Integration:
HACS
```
Integration version: | 1.29.0
Frontend version: | 20220906112053
```
Tinxy
(master) of this repo

Firmware version: 3.2

Response from `/devices` API:
```
           "numberOfRelays": 4,
            "name": "WIFI_4SWITCH",
            "__v": 1,
            "gtype": "action.devices.types.SWITCH",
            "traits": [
                "action.devices.traits.OnOff"
            ],
            "long_name": "4 node Smart Switch",
            "amazonReviewLink": "https://www.amazon.in/review/create-review/?asin=B07PCS8W5R",
            "features": [
                "SWITCH",
                "SWITCH",
                "SWITCH",
                "SWITCH"
            ],
```

**Comment by shashwat** [comment]
Might be related to this, I also observed this:
https://forum.tinxy.in/t/device-toggle-api-returning-internal-server-error-when-trying-to-turn-on-the-switch/631

I believe there is version incompatibility b/w Latest API and Firmware version  ?

**Comment by shashwat** [comment]
If that is the case, shall I upgrade the firmware to 5.x. And is it safe to do so ?

**Comment by arevindh** [comment]
> If that is the case, shall I upgrade the firmware to 5.x. And is it safe to do so ?

That might be the issue, try upgrading. If you encounter any problems call customercare

**Comment by shashwat** [comment]
Yes. Upgrading fixed it. Thanks.
