### ISSUE TITLE
installation unknown_error 

### ISSUE THREAD

**Issue by solancer** [arevindh/tinxy-hacs#16]
Get's stuck on the install screen

<img width="1440" alt="Screenshot 2023-03-14 at 5 31 14 AM" src="https://user-images.githubusercontent.com/800668/224858257-5882a94c-7365-47d3-bd4f-072b600ddeb3.png">

**Comment by arevindh** [comment]
Try the manual method.

**Comment by arevindh** [comment]
@solancer got it working ?

**Comment by solancer** [comment]
@arevindh Yep, manual downloading and unzipping the files worked. Thanks for putting this together. I will connect this to Rhasspy assistance for replacing all my Alex devices at home.
