### ISSUE TITLE
Toggle switch is not working

### ISSUE THREAD

**Issue by sachinvaishnav** [arevindh/tinxy-hacs#19]
I have Tinxy 16A switch which was working perfectly on Home Assitant until recently. I had a few automation creted based on the toggle state and it was all ok. This morning I noticed that the "state" is not getting updated in HA. 
- Tried turning on the switch via HA. It turned on the switch (confirmed with Tinxy App too). However, STATE within HA kept showing OFF. Automation (obviously) did not get triggered
- Tried turning off the switch via HA. It did nothing. Confirmed with Tinxy app too. State, continued as off. 
- Tried turning on the switch via Tinxy App. Nothing changed on HA. STATE remained off. 

Something seems broken. Any help would be greatly appreciated!

**Comment by arevindh** [comment]
@sachinvaishnav It was a configuration issue on the Tinxy side, seems fixed now.
