### ISSUE TITLE
Unable to Toggle Fan On/Off - 4 Node Switch with Fan Controller 

### ISSUE THREAD

**Issue by abufaisalrk** [arevindh/tinxy-hacs#20]
Hi, 
I recently integrated the 4 node with Fan controller in HA and the device shows up fine. However, when I toggle the fan On I get the below error.  The fan turns on if I directly select the speed Low/Medium/High, but I can't toggle the fan on/off. 

Failed to call service fan/turn_on. TinxySwitch.async_turn _on() takes 1 positional argument but 3 were given

**Comment by arevindh** [comment]
> Hi, I recently integrated the 4 node with Fan controller in HA and the device shows up fine. However, when I toggle the fan On I get the below error. The fan turns on if I directly select the speed Low/Medium/High, but I can't toggle the fan on/off.
> 
> Failed to call service fan/turn_on. TinxySwitch.async_turn _on() takes 1 positional argument but 3 were given

Which version are you using?

HA Version , Plugin Version

**Comment by abufaisalrk** [comment]
HA Version
Core: 2023.12.1
Supervisor: 2023.11.6
Operating System: 11.2
Frontend: 20231208.2

Tinxy Plugin: 3.0.5

**Comment by PatelTilak** [comment]
It seems like some waa changed recently.
It used to work fine for me since more than a month. Now getting error for fan. Lights controls work fine

**Comment by arevindh** [comment]
> It seems like some waa changed recently.
> It used to work fine for me since more than a month. Now getting error for fan. Lights controls work fine

Which device do you have ?

**Comment by PatelTilak** [comment]
Providing more details to ease triaging.
Toggle ON switch does not work. OFF works fine. Also, speed change is working fine. If fan is off & we toggle speed, it does turn on fan with the specified speed.

Thia might be related to HA 2023.12 release breaking changes.

**Comment by PatelTilak** [comment]
> > It seems like some waa changed recently.
> > It used to work fine for me since more than a month. Now getting error for fan. Lights controls work fine
> 
> Which device do you have ?

4+1 fan controller

**Comment by arevindh** [comment]
@PatelTilak @abufaisalrk Can try to update to 3.0.6.

**Comment by PatelTilak** [comment]
> @PatelTilak @abufaisalrk Can try to update to 3.0.6.

Fixed after updating to 3.0.6

**Comment by abufaisalrk** [comment]
> @PatelTilak @abufaisalrk Can try to update to 3.0.6.

Thanks! It is working after the update.
