### ISSUE TITLE
Tinxy Lock V3 Door open/closed sensor not showing 

### ISSUE THREAD

**Issue by nishant713** [arevindh/tinxy-hacs#21]
Device : WIRED_D0OR_LO CK_V3 V7 
Issue : 
a. The device has a door closes/opened sensor but the same is not polled in Home Assistant integration. 
![Screenshot_20240615-133405](https://github.com/arevindh/tinxy-hacs/assets/1642480/81ca782d-3203-468e-bd74-f866146d71de)
b. Door lock/unlock operation works fine.

**Comment by arevindh** [comment]
#22
