### ISSUE TITLE
As a beginner to home assistant i have no idea how to integrate this and use tinxy with home assistanht

### ISSUE THREAD

**Issue by soorya13344** [arevindh/tinxy-hacs#3]

**Comment by arevindh** [comment]
Install Hacs [https://hacs.xyz/](https://hacs.xyz/) 
Add this project as custom repository  [https://hacs.xyz/docs/faq/custom_repositories](https://hacs.xyz/docs/faq/custom_repositories)

**Comment by soorya13344** [comment]
I'm a complete beginner in home assistant and I'm finding it very difficult to use the integration. I'm not able to figure out how to use the API key.

**Comment by soorya13344** [comment]
i got as far as installing hacs and adding tinxy as an integration into hacs.

**Comment by arevindh** [comment]
Open your `configuration.yaml`

and paste the following on a  new line (replace the API key)

```
switch:
  - platform: tinxy
    api_key : 12345678901234567890
    scan_interval: 10
```

Restart home assistant 

Check `developer-tools` for new entity

**Comment by soorya13344** [comment]
I'm sorry but I have no experience with codes. i just started
am I supposed to open that in the web GUI or the server device?

**Comment by arevindh** [comment]
@soorya13344 do use have `vscode` addon installed?

**Comment by arevindh** [comment]
We have a discord server if you like to join

**Comment by soorya13344** [comment]
nope I only installed ssh code for the hacs installation

**Comment by arevindh** [comment]
We have a discord server if you like to join, which consists of Home Automation enthusiasts from all over India
[Home Automation India](https://discord.gg/THU4AgBp)

**Comment by soorya13344** [comment]
oh thank you

**Comment by arevindh** [comment]
Vscode guide : https://www.youtube.com/watch?v=m65ImtmOyC8

**Comment by soorya13344** [comment]
I finally figured it out. Thank you very much that was really helpful. : )
