### ISSUE TITLE
Can't add switches to homeassistant

### ISSUE THREAD

**Issue by karan1125** [arevindh/tinxy-hacs#5]
I have managed to install Tinxy repository through HACS, but now I am stuck because I can't add or access my switches through homeassistant.. please help!

**Comment by karan1125** [comment]
Hey, i checked out an earlier thread where you explained the process to someone and i was able to add the switches following your instructions and control them. Now I have have another issue, I can't see those switches when I'm trying to create an automation, how do I make the switches available in automation? 

Also if you dont mind I would like to join the discord where home automation in india is discussed.

**Comment by arevindh** [comment]
@karan1125 sure you can join

**Comment by karan1125** [comment]
Could you please send me the invite link?

**Comment by arevindh** [comment]
@karan1125 https://discord.gg/CcCMU5AM

**Comment by cmdev007** [comment]
@arevindh I am facing the exact same issue. Can you please help or give the discord link?

**Comment by arevindh** [comment]
> @arevindh I am facing the exact same issue. Can you please help or give the discord link?

Did you add those lines in config yaml?

**Comment by arevindh** [comment]
@cmdev007 you can join Tinxys official discord , will meet you there 
https://discord.gg/3rqQv2Zd

**Comment by rh05-bellavista** [comment]
Hi I am new to Home Assistant and also Tinxy.
I have used the user interface to add tinxy repositry into HACS

I could not see my devices for controlling/scripting from Home Assist. This looks like a common question above but could not find steps.. i believe there are some steps which I may have missed. please assist.

Also, please send me an invite for the discord.

**Comment by ManivannanBA** [comment]
I am also new to Tinxy and trying to integrate with Home Assistant. I have installed the custom component but am unsure about adding the keys to the custom component.

**Comment by arevindh** [comment]
> I am also new to Tinxy and trying to integrate with Home Assistant. I have installed the custom component but am unsure about adding the keys to the custom component. 

You have to add vscode addon and edit the configuration.yaml file

**Comment by arevindh** [comment]
Updated  Read me 
https://github.com/arevindh/tinxy-hacs/blob/main/README.md
